### ISSUE TITLE
Request to the author

### ISSUE THREAD

**Issue by abu-mik** [michaelpm54/Ace3x#1]
Good afternoon!
I apologize for the rather unsuccessful way to contact you (I did not find another) and my bad English (I am Russian).
I am extremely interested in your project Ace3x regarding the extraction of TGA files from Summoner 2 modules. If possible, publish a link to the executable Ace3x.
Grateful in advance, Iogan.

**Comment by michaelpm54** [comment]
Sorry, I thought I had my email address on my page.

Here is a link to the exe in a zip: https://drive.google.com/file/d/1F6tRjoTCjMorC9FWIa7pNSXd20ki7tI6/view?usp=sharing

Please let me know if something doesn't work.
